_schema: _schema
paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config_override: false
_inputs:
  menu_category:
    type: select
    options:
      allow_empty: true
      values:
        - Hor d'oeuvres
        - Stations
        - Trays
        - Soup, Salads, and Dips
        - Entree
    cascade: true
  release_date:
    type: date
    cascade: true
  expiration_date:
    type: date
    cascade: true
  start:
    type: datetime
    cascade: true
  end:
    type: datetime
    cascade: true
  image-1:
    type: image
    cascade: true
  image-2:
    type: image
    cascade: true
  image-3:
    type: image
    cascade: true
  page_banner:
    type: image
    cascade: true
  beverage_banner:
    type: image
    cascade: true
  logo:
    type: image
    cascade: true
  background_image:
    type: image
    cascade: true
  background_image_2:
    type: image
    cascade: true
  background_image_3:
    type: image
    cascade: true
_editables:
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: false
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    resize_style: cover
    right: text-right
    styles: /assets/css/theme.css
    table: true
    underline: true
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    copyformatting: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: false
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    redo: true
    removeformat: true
    resize_style: cover
    right: text-right
    styles: /assets/css/theme.css
    table: true
    underline: true
  sub-page:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    copyformatting: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: false
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    redo: true
    removeformat: true
    resize_style: cover
    right: text-right
    styles: /assets/css/theme.css
    table: true
    underline: true
timezone: Etc/UTC
data:
  path: _data
  output: false
posts:
  path: _posts
  output: true
  create:
    path: >-
      [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
pages:
  path: ''
  output: true
  filter: strict
properties:
  output: true
  path: _properties
schemas:
  block_page:
    path: schemas/page.md
    reorder_inputs: true
    hide_extra_inputs: false
    remove_empty_inputs: false
    remove_extra_inputs: true
    icon: notes
    _enabled_editors:
      - visual
      - content
  content_page:
    path: schemas/property.md
    reorder_inputs: true
    hide_extra_inputs: false
    remove_empty_inputs: false
    remove_extra_inputs: true
    icon: notes
    _enabled_editors:
      - content
      - visual
